name: Say Hi!

on: 
  - push
  - workflow_dispatch

jobs:
  say-hi-job:
    runs-on: self-hosted-hello
    steps:
      - name: Cow Say Hello Please!
        run: cowsay "Hello UAB ShareOps!"
      - name: Inspire please!
        run: fortune | cowsay